version: "3"

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./logs/php:/var/log/php
    networks:
      - app-network

  webserver:
    image: nginx:latest
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: opencart
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
      - ./logs/mysql:/var/log/mysql
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
